language: php
php:
  - 5.6

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install

script:
  - phpunit
  
after_success:
  - travis_retry php vendor/bin/coveralls
